import { commits, isTagCommit, setCommit, getTagCommit } from './git';
import { Commit, GeneriEmoticon, GeneriOptions, Root } from './types';
import { setChangelog } from './utils';
import conventional from './defines/conventional-commits.json';

const getEmoji = (str: string): string => {
	const emojis: GeneriEmoticon[] = [
		['feat', '🎉 '],
		['fix', '🔧 '],
		['build', '📐 '],
		['chore', '🚧 '],
		['ci', '🗿 '],
		['style', '🎨 '],
		['refactor', '🚩 '],
		['perf', '📈 '],
		['docs', '📝 '],
		['test', '🔧 '],
	];

	const target = emojis.find(([key]) => str.includes(key));

	return target ? target[1] : '  ';
};

const getChangelogHeader = () => {
	return `# Changelog (${new Date().toLocaleDateString()})\n\nChangelog was generated by [Generi](https://github.com/betterwrite/generi). Any questions, consult the documentation.\n`;
};

const setSubHeader = (commit: Commit) => {
	const v = isTagCommit(commit)
		? getTagCommit(commit)
		: commit.summary.replace(/'/gi, '');

	if (v.trim().startsWith('origin/')) return '';

	return '\n### ' + v + '\n\n';
};

const setBasic = (commit: Commit, config: GeneriOptions) => {
	let result: string[] | string;

	if (config.commits === 'conventional-commits') {
		result = commit.summary
			.split(/:(.+)/)
			.filter((part) => part)
			.map((part) => part.trimStart());
	} else {
		result = commit.summary;
	}

	const sha =
		config?.repository && config?.repository !== 'ignore'
			? ` - [[${commit.sha}](${config.repository}/commit/${commit.sha})]`
			: '';

	if (config.commits === 'conventional-commits') {
		if (!result[0] || !result[1]) return '';

		return (
			'* **' +
			getEmoji(result[0]) +
			result[0].trim() +
			':** ' +
			result[1].trim() +
			sha +
			'\n'
		);
	}

	if (isTagCommit(commit)) return '';

	return '* ' + (result as string).trim() + sha + '\n';
};

const isConventionalCommit = (commit: Commit): boolean => {
	return conventional.type.some((type) => commit.summary.trim().startsWith(type));
};

export const setActuallyTag = (tag: string) => {
	return setSubHeader({
		summary: tag,
		sha: '__DEFAULT__',
		refName: [],
		date: '__DEFAULT__',
	});
};

export const createChangelog = (tag: string, { config, console }: Root) => {
	const exclude = config?.exclude ?? [' typo'];

	let changelog = getChangelogHeader();

	if (config.tag) changelog += setActuallyTag(tag);

	commits().forEach((commit) => {
		if (exclude.some((c) => commit.summary.includes(c))) return;

		if (isTagCommit(commit)) {
			changelog += setSubHeader(commit);
			return;
		}
		if (!isConventionalCommit(commit) && config.commits === 'conventional-commits')
			return;

		changelog += setBasic(commit, config);
	});

	setChangelog(changelog);

	setCommit(config.tag ? tag : 'chore(generi): generate changelog.md', true, console);

	console.success('Generate CHANGELOG.md');
};
